### ISSUE TITLE
🐛Expense register modal without style after upgrade to version v0.9.0

### ISSUE THREAD

**Issue by josuegodoy** [budgetbee/budgetbee#104]
**Describe the bug**
After upgrading to version v0.9.0 the creating expense modal window has no background and styles.

**To Reproduce**
1. Upgrade to v0.9.0 version
2. Click on "New record" button to register new expense
3. The Window loads crashed like print screen
4. Same error on Edit Expense Window

**Expected behavior**
CSS fix.

**Screenshots**
![image](https://github.com/user-attachments/assets/8d6fa9b3-82fe-4257-8927-4794eb7e1d46)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome, Edge
 - Version: 128.0.6613.85

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2020
 - OS: iOS 17.5.1
 - Browser:  Chrome
 - Version: 128.0.6613.92

**Additional context**
At mobile version error not ocurred.

**Comment by HadryXx** [comment]
Same for me, and now if I rollback to a previous version the view looks just as bad, without style.

**Comment by Pelukosa** [comment]
It has been fixed by revert the last commit in v0.9.1, soon there will be an update to re-implement the rules, sorry for the inconvenience!
