### ISSUE TITLE
🐛Add new records window transparent. 

### ISSUE THREAD

**Issue by mrp-yt** [budgetbee/budgetbee#105]
**Describe the bug**
When i click on "New record" - transparent window shows up. 
[Running via Docker Compose]

**To Reproduce**
1. Go to 'main page'
2. Click on 'New Record'

**Expected behavior**
New record entry window to be NOT transparent. 
I have tried to set everything from scratch to check if that will go away

**Screenshots**
https://prnt.sc/RJJ-zR2RRckv

**Desktop (please complete the following information):**
 - OS: [Windows/Linux]
 - Browser [edge, chrome]
 - Version [edge/chrome v=128]

**Comment by Pelukosa** [comment]
It has been fixed by revert the last commit in the v0.9.1, soon there will be an update to re-implement the rules, sorry for the inconvenience!
