### ISSUE TITLE
Cant create first user

### ISSUE THREAD

**Issue by BeeTwenty** [budgetbee/budgetbee#24]
**Describe the bug**

 SQLSTATE[42S02]: Base table or view not found: 1146 Table 'budgetbee.users'
   doesn't exist

**To Reproduce**
1. Start fresh docker
2. Run create user script
3. Error

**Expected behavior**
User should be created

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] ubuntu 22.4
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Pelukosa** [comment]
Hello!

Try to exec this from your  machine:

`docker exec budgetbee-webserver-1 ./entrypoint.sh
`

And then, exec the user command again

**Comment by titostl1** [comment]
I just ran into this myself. I  changed the dash to and underscored to solve the issue.  `docker exec budgetbee_webserver_1 php scripts/create_user.php <your_name> <your_email> <your_password>`

**Comment by BeeTwenty** [comment]
'''docker exec budgetbee-webserver-1 ./entrypoint.sh
OCI runtime exec failed: exec failed: unable to start container process:
exec ./entrypoint.sh: no such file or directory: unknown
***@***.***:/home/beetwenty# docker exec budgetbee-webserver-1
./entrypoint.sh
OCI runtime exec failed: exec failed: unable to start container process:
exec ./entrypoint.sh: no such file or directory: unknown'''

Also tried undrrscore and then it cant fond the container

man. 17. jul. 2023, 02:22 skrev titostl1 ***@***.***>:

**Comment by Pelukosa** [comment]
I will check this error

So you don't have to wait for this fix to arrive, change the line of the docker-compose of the webserver container 

command: sh entrypoint.sh by command: php-fpm

Once the containers are up and working try this:

docker exec budgetbee-webserver-1 php artisan migrate --force --seeded

**Comment by BeeTwenty** [comment]
docker exec budgetbee-webserver-1 php artisan migrate --force --seeded
  The "--seeded" option does not exist.

man. 17. jul. 2023, 09:45 skrev Alejandro Recio ***@***.***>:
