### ISSUE TITLE
[BUG] Unable to save or add any Transfer, Income or Expense

### ISSUE THREAD

**Issue by mariushosting** [budgetbee/budgetbee#34]
The V button to save is not working.

**Comment by Pelukosa** [comment]
Hi!

Update to latest version (v.0.2.0) and try again

**Comment by mariushosting** [comment]
Solved!

**Comment by mariushosting** [comment]
Tested today a fresh installation can't create any accounts.

**Comment by mariushosting** [comment]
![Screenshot 2023-07-25 14 29 05](https://github.com/budgetbee/budgetbee/assets/37554361/961b766f-9bc3-40bc-8f88-370da0f4731a)
![Screenshot 2023-07-25 14 29 08](https://github.com/budgetbee/budgetbee/assets/37554361/26752659-638e-4e86-9ff0-145cdfefc69f)

The button does not save anything

**Comment by TomasZmek** [comment]
@mariushosting  I saw a Bug created here. -> https://github.com/budgetbee/budgetbee/issues/41

**Comment by Pelukosa** [comment]
Fixed in [version v0.2.1](https://github.com/budgetbee/budgetbee/releases/tag/v0.2.1)
