### ISSUE TITLE
[FEATURED] Currency settings

### ISSUE THREAD

**Issue by TomasZmek** [budgetbee/budgetbee#35]
Option to set a currency other than USD for each account.
Setting the currency for payment
Enable currency management
Add, edit and delete currency.
Setting the conversion rate
Option to select a default currency

**Comment by TomasZmek** [comment]
The conversion rate is important to convert to the default currency that should display the amounts in the dashboard

**Comment by Pelukosa** [comment]
Yes, this is a must in the project, but thanks for creating this issue, I use it for development

**Comment by pawisoon** [comment]
It would be fantastic to get this feature in as soon as possible!
