### ISSUE TITLE
[BUG]  - can not create accounts

### ISSUE THREAD

**Issue by ahmaddxb** [budgetbee/budgetbee#41]
**Describe the bug**
can not create accounts

fresh install of v0.2.0

**To Reproduce**
1. Go to 'Account'
2. Click on 'Create New'
3. fill in account detail and click the tick
4. account list is still empty, account was not created

**Expected behavior**

**Screenshots**
![image](https://github.com/budgetbee/budgetbee/assets/43728586/19bda2f2-664d-48d8-8c61-52085afaf349)

![image](https://github.com/budgetbee/budgetbee/assets/43728586/c67e7a60-14e0-48b4-bdd6-b76f7a5383e1)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome, firefox

**Additional context**

**Comment by TomasZmek** [comment]
I confirm this behaviour. Vivaldi browser

`{
    "message": "Request failed with status code 422",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 422\n    at settle (https://penize.zrnek.cz/static/js/bundle.js:104005:12)\n    at XMLHttpRequest.onloadend (https://penize.zrnek.cz/static/js/bundle.js:102696:66)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json",
            "Authorization": "Bearer 6|x2xwUYPwJpAXgphId0Z6AfF9fVRTlLqH19ehteUu"
        },
        "method": "post",
        "url": "/api/account/",
        "data": "{\"name\":\"pokus\",\"initial_balance\":\"100\"}"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 422
}`

**Comment by Pelukosa** [comment]
Fixed in [version v0.2.1](https://github.com/budgetbee/budgetbee/releases/tag/v0.2.1)
