### ISSUE TITLE
[BUG] api container entrypoint.sh fails to run

### ISSUE THREAD

**Issue by joeclifford** [budgetbee/budgetbee#43]
**Describe the bug**
[entrypoint.sh](https://github.com/budgetbee/budgetbee/blob/main/api/entrypoint.sh) fails to run at container start as the script requires /bin/bash to run, but the container does not included the bash package

**To Reproduce**
1. Delploy budgetbee via docker-compose
2. follow the `docker exec budgetbee-webserver-1 php scripts/create_user.php <your_name> <your_email> <your_password>` instructions
3. See error:
```

In Connection.php line 795:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'budgetbee.users'
   doesn't exist (Connection: mysql, SQL: select count(*) as aggregate from `
  users` where `email` = joe@cliffsy.co.uk)


In Connection.php line 416:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'budgetbee.users'
   doesn't exist
```

**Expected behavior**
```
User created successfully!
```

**Additional context**
The api container doesn't contain bash
```
joe@linux-docker-01 [ ~ ]$ docker exec -it budgetbee-webserver-1 /bin/sh
/var/www/html $ which sh
/bin/sh
/var/www/html $ which bash
/var/www/html $
```

The `entrypoint.sh` script interpreter is calling `/bin/bash`
```
/var/www/html $ cat ./entrypoint.sh
#!/bin/bash

# Sleep for wait to db container
sleep 20;

# Run key:generate
# php artisan key:generate

# Run migrate --seed
php artisan migrate --force --seed

# Start the PHP-FPM server
php-fpm/var/www/html $
```

**Comment by Pelukosa** [comment]
@radguru I appreciate your work so much!
Thank you for the fix!
