### ISSUE TITLE
[BUG] Many "Cannot read properties of undefined" errors when loading

### ISSUE THREAD

**Issue by edersong** [budgetbee/budgetbee#53]
**Describe the bug**
Deployed BudgetBee using the [docker-compose.yml](https://github.com/budgetbee/budgetbee/blob/main/docker-compose.yml) and [.env.example](https://github.com/budgetbee/budgetbee/blob/main/.env.example) changing the environment settings as required but when trying to open the app it try to load and report many "Cannot read properties of undefined" errors.

**To Reproduce**
1. Deploy the docker-compose.yml and .env files 
2. Open the gui page
3. See error

**Expected behavior**
Open the GUI to work on the app

**Screenshots**
![image](https://github.com/budgetbee/budgetbee/assets/64137913/92df8cdb-66c8-4618-8c43-edaabee29fd3)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome version 116.0.5845.96

**Additional context**
Entire log attached here 
[logs.txt](https://github.com/budgetbee/budgetbee/files/12394852/logs.txt)

Realized that the readme instructions are outdated, so I think that need an additional step after deploy that is not documented yet.
If so, please provide instructions to complete deployment.
Thank you in advance.

**Comment by edersong** [comment]
Hi Alejandro,
Thank you for the feedback!
I deployed using [docker-compose.yml](https://github.com/budgetbee/budgetbee/blob/main/docker/docker-compose.yml) file but when trying to run docker exec command instructed, it fails with the following error message:

`In Connection.php line 795:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'budgetbee.users'
   doesn't exist (Connection: mysql, SQL: select count(*) as aggregate from `
  users` where `email` = email@gmail.com)

In Connection.php line 416:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'budgetbee.users'
   doesn't exist
`

**Comment by Pelukosa** [comment]
You need wait around 30s seconds after deploy while the database setup. Try now again

**Comment by rakuri255** [comment]
I also becoming the same error when using the compose from @Pelukosa.

**Comment by rakuri255** [comment]
Nope. Still doesnt work
