### ISSUE TITLE
ERROR can't convert undefined to object[BUG]

### ISSUE THREAD

**Issue by Leen58** [budgetbee/budgetbee#60]
Installed BudgetBee in Synology Docker. Created the databases and the superuser. 
Started Budgetbee. 
Got the opening screen

![afbeelding](https://github.com/budgetbee/budgetbee/assets/70329246/c083ff63-5f3e-40b5-a8a6-5a350e55f2ba)

After some 2 seconds spinning got the following error: ERROR can't convert undefined to object

![afbeelding](https://github.com/budgetbee/budgetbee/assets/70329246/22d9bd64-786c-4f86-97a1-bc0dc0fa5be3)

**Comment by SergioZgz** [comment]
I cannot create the user.... also using a synology nas hehe 

Did you changes something in docker script?

**Comment by Leen58** [comment]
No i did not change anything in the script.

Op vr 29 sep. 2023 23:08 schreef SergioZgz ***@***.***>:

**Comment by Ghostscare** [comment]
I have the same problem. Did you find a fix for it?
