### ISSUE TITLE
🐛php artisan migrate --force is not fully working anymore in Docker version 0.7.0

### ISSUE THREAD

**Issue by mariushosting** [budgetbee/budgetbee#91]
2023_08_04_181743_create_default_user_currency never finish so the migration can't be done.

![issue](https://github.com/budgetbee/budgetbee/assets/37554361/53cfef4f-b8c7-4841-bbac-84223793b699)

Actually version 0.7.0 can't be installed @Pelukosa

**Comment by Pelukosa** [comment]
This migration sleeps for 5 seconds, so you might need to give it another 10 seconds or so to be sure it's finished.
![Screenshot_6](https://github.com/budgetbee/budgetbee/assets/20848123/d52839a8-55dd-4d3f-9db8-12c434549e52)

**Comment by mariushosting** [comment]
> This migration sleeps for 5 seconds, so you might need to give it another 10 seconds or so to be sure it's finished. ![Screenshot_6](https://private-user-images.githubusercontent.com/20848123/300953488-d52839a8-55dd-4d3f-9db8-12c434549e52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NDc1MDcsIm5iZiI6MTcwNjY0NzIwNywicGF0aCI6Ii8yMDg0ODEyMy8zMDA5NTM0ODgtZDUyODM5YTgtNTVkZC00ZDNmLTlkYjgtMTJjNDM0NTQ5ZTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDIwNDAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5OWY2ZmUwMjRkYWQ4YWU1NzZlOWQ3NDk3YWRjYmUwNmI3MTk3MDRmY2EyNGZiNzBjMDFmYTM0NWZlMmYwZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.55ix88IuSRJMk5b7ZDwTrYgOdxdnUIquDWug7ZfXNmQ)

Unfortunately, it sleeps indefinitely. I've left it alone and checked after 2 hours and no change. The issue was already reported by 154 users using my guide here: https://mariushosting.com/how-to-install-budgetbee-on-your-synology-nas/

No issue with version 0.6.0

**Comment by mariushosting** [comment]
I confirm the fix you have applied is working! Thank You @Pelukosa
